### PR TITLE
[PHP 8.4]: Fixing deprecation warning on implicit nullable parameters

### PR DESCRIPTION
**Pull request by ThomasLandauer**

### CODE REVIEW

**Comment by mlocati** [comment]
Will this work with [PHP 5](https://github.com/mlocati/idna/blob/1.1.2/composer.json#L51)?

**Comment by ThomasLandauer** [comment]
Probably not. But 5.3 is EOL since 10 years: https://www.php.net/eol.php So sooner or later you need to decide if you wanna support ancient or current versions, cause you can't have both ;-)

**Comment by mlocati** [comment]
I'm not saying we shouldn't drop support for PHP 5: we just have to declare it 😉

**Comment by mlocati** [comment]
Thanks! I adjusted the tests and composer.json file in #13

**Pull request closed without merging**
